
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpjpvlzylwrpmnpxwoij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwanB2bHp5bHdycG1ucHh3b2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzM1MDAsImV4cCI6MjA2MjgwOTUwMH0.BkaTMlSim6r04v4m9ps516UyVeD_hJgazKxoDWyCwjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage,
      detectSessionInUrl: true,
      flowType: 'implicit'
    }
  }
);
