
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bndyewjmbkznimtrqmuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuZHlld2ptYmt6bmltdHJxbXV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzgyNjMsImV4cCI6MjA2MzcxNDI2M30.azhQKA0K57JBGwKdraY4TD0lkRlfq5jT-W4PFJ8Ghqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage,
      detectSessionInUrl: true,
      flowType: 'implicit'
    }
  }
);
